[book]
authors = ["Einar W. Høst", "Daan van Berkel"]
language = "en"
multilingual = false
src = "src"
title = "Circle Limit III; come full circle"

[output.html]
mathjax-support = true
additional-css = ["custom.css"]
